#!/usr/bin/env bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE nuxeo PASSWORD 'md5ea3a0e98dc3270f010c1b8613e098617' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;
	CREATE DATABASE nuxeo ENCODING 'UTF8' OWNER nuxeo;
	GRANT ALL PRIVILEGES ON DATABASE nuxeo TO nuxeo;
EOSQL
