{
 "title": "Nuxeo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nuxeo nodes",
   "type": "singlestat",
   "description": "The number of Nuxeo nodes in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.nuxeo.instance-up.count)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "description": "The number of errors in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.{error,fatal}.count)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "description": "The number of warnings in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.warn.count)"
    }
   ]
  },
  {
   "title": "All",
   "type": "singlestat",
   "description": "The Nuxeo's log activity for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.all.count)"
    }
   ]
  },
  {
   "title": "Errors and warnings",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.error.count, 9)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.fatal.count, 9)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.logging.log4j.core.Appender.warn.count, 9)"
    }
   ]
  },
  {
   "title": "Stream Failure",
   "type": "singlestat",
   "description": "The number of Stream processing computation terminated due to failure after applying the retry policy. A manual restart of Nuxeo is required to continue the processing, this must be done within the stream retention policy (7 days by default when using Kafka).",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.nuxeo.streams.failure.count)"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.jvm.threads.*.count, 1), 4)"
      }
     ]
    },
    {
     "title": "Threads per JVM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.threads.count, 1)"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.heap.usage, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.*.used, 1, 5)"
      }
     ]
    },
    {
     "title": "Garbage Collector",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.G1-Young-Generation.time, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.G1-Old-Generation.time, 1, 5)"
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.buffers.*.used, 1, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.bytesReceived, 1), 3)"
      },
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.bytesSent, 1), 3)"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.currentThreadBusy, 1), 3)"
      },
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.currentThreadCount, 1), 3)"
      }
     ]
    },
    {
     "title": "JDBC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.jdbc-numActive, 1), 3)"
      },
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.jdbc-numIdle, 1), 3)"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.requestCount, 1), 3)"
      },
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.tomcat.errorCount, 1), 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Repository",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.sessions, 1)"
      }
     ]
    },
    {
     "title": "Connections JDBC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.repository.jdbc.nuxeo.connection.*, 1, 9)"
      }
     ]
    },
    {
     "title": "Documents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.repository.default.documents.*.count, 1, 8)"
      }
     ]
    },
    {
     "title": "Queries and Saves",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.repository.default.{query,save}.count, 1, 7)"
      }
     ]
    },
    {
     "title": "Transactions concurrency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.concurrency.count, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.concurrency.max.count, 1, 5, 6)"
      }
     ]
    },
    {
     "title": "Transactions count and rollback",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.rollbacks.count, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.timer.count, 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Elasticsearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastic throughputs 1min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.timer.m1_rate, 1, 6)"
      }
     ]
    },
    {
     "title": "Elastic counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.timer.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Elastic timers p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.timer.p50, 1, 6)"
      }
     ]
    },
    {
     "title": "Elastic timers p98",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 76 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.timer.p98, 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo WorkManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Works completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.global.queue.*.completed, 1, 7)"
      }
     ]
    },
    {
     "title": "Works scheduled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.global.queue.*.scheduled, 1, 7)"
      }
     ]
    },
    {
     "title": "Work timers p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.queue.*.timer.p50, 1, 6)"
      }
     ]
    },
    {
     "title": "Work timers p98",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 93 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.queue.*.timer.p98, 1, 6)"
      }
     ]
    },
    {
     "title": "Works throuhgputs 1min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.queue.*.timer.m1_rate, 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Position",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(servers.*.nuxeo.nuxeo.streams.global.stream.audit.group.AuditLogWriter.pos, 'current pos')"
      },
      {
       "target": "alias(servers.*.nuxeo.nuxeo.streams.global.stream.audit.group.AuditLogWriter.end, 'end')"
      }
     ]
    },
    {
     "title": "Audit Lag and Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(servers.*.nuxeo.nuxeo.streams.global.stream.audit.group.AuditLogWriter.lag, 'lag')"
      },
      {
       "target": "alias(servers.*.nuxeo.nuxeo.streams.global.stream.audit.group.AuditLogWriter.latency, 'latency')"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream processor in failure",
     "type": "graph",
     "description": "Nuxeo node with failure needs to be restarted.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(currentAbove(servers.*.nuxeo.nuxeo.streams.computation.*.failure.count, 0), 2, 6)"
      }
     ]
    },
    {
     "title": "Records skipped due to failure",
     "type": "graph",
     "description": "This count the number of records skipped because the computation policy is configured to continue on failure. This requires some attention to understand why these records have been skipped.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "records" }
     ],
     "targets": [
      {
       "target": "aliasByNode(currentAbove(servers.*.nuxeo.nuxeo.streams.computation.*.skippedRecord.count, 0), 2, 6)"
      }
     ]
    },
    {
     "title": "Streams Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.streams.global.stream.*.group.*.lag, 7, 9)"
      }
     ]
    },
    {
     "title": "Streams Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.streams.global.stream.*.group.*.latency, 7, 9)"
      }
     ]
    },
    {
     "title": "Most deviant Lag",
     "type": "graph",
     "description": "The 5 most deviant lag per partition.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(mostDeviant(servers.*.nuxeo.nuxeo.streams.global.stream.*.group.*.lag, 5), 7, 9)"
      }
     ]
    },
    {
     "title": "Streams Positions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.streams.global.stream.*.group.*.pos, 7, 9)"
      }
     ]
    },
    {
     "title": "Slowest record processing",
     "type": "graph",
     "description": "The 5 slowest computations when processing record (mean).",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.streams.computation.*.processRecord.mean, 5), 2, 6)"
      }
     ]
    },
    {
     "title": "Top throughput records/min",
     "type": "graph",
     "description": "The 5 computations that process the most record per minute.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 36 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.streams.computation.*.processRecord.m1_rate, 5), 2, 6)"
      }
     ]
    },
    {
     "title": "Slowest timer processing",
     "type": "graph",
     "description": "The 5 slowest computations when processing their timer (mean).",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 44 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestAverage(servers.*.nuxeo.nuxeo.streams.computation.*.processTimer.mean, 5), 2, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Auth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.web.authentication.logged-users.count, 1, 6)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.web.authentication.requests.timer.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Cache Hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.cache.*.hit.ratio, 1, 5)"
      }
     ]
    },
    {
     "title": "Directories sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.directory.*.sessions.active.count, 1, 6, 7)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.directory.*.sessions.max.count, 1, 6, 7, 8)"
      }
     ]
    },
    {
     "title": "Directories cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.directory.*.cache.size.count, 1, 5)"
      }
     ]
    }
   ]
  }
 ]
}