---
- hosts: all
  gather_facts: no
  vars_files:
    - [ "group_vars/all/nuxeo-{{ nuxeo_select_version }}.yml" ]
  vars:
    - nuxeo_templates: ['default']
    - nuxeo_nodes: []
  pre_tasks:
    - name: Mongo template
      set_fact:
        nuxeo_templates: "{{ nuxeo_templates  + ['mongodb']}}"
      when: "mongo"
    - name: PostgreSQL template
      set_fact:
        nuxeo_templates: "{{ nuxeo_templates  + ['postgresql']}}"
      when: "postgres"
    - name: Redis template
      set_fact:
        nuxeo_templates: "{{ nuxeo_templates  + ['redis']}}"
      when: "redis and (nuxeo_version is version_compare('9.10', '>'))"
    - name: Kafka Confluent template
      set_fact:
        nuxeo_templates: "{{ nuxeo_templates  + ['/templates/confluent']}}"
      when: "kafkaconfluent"
    - name: Nuxeo standalone
      set_fact:
        nuxeo_nodes: ['nuxeo']
      when: "nuxeo_nb_nodes == '1'"
      tags:
        - test
    - name: 2 Nuxeo nodes
      set_fact:
        nuxeo_nodes: ['nuxeo', 'nuxeo2']
      when: "nuxeo_nb_nodes == '2'"
      tags:
        - test
    - name: 3 Nuxeo nodes
      set_fact:
        nuxeo_nodes: ['nuxeo', 'nuxeo2', 'nuxeo3']
      when: "nuxeo_nb_nodes == '3'"
      tags:
        - test
    - name: Nuxeo template
      debug: var=nuxeo_templates
    - name: Nuxeo node names
      debug: var=nuxeo_nodes
  roles:
    - common
