{
 "title": "Nuxeo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nuxeo nodes",
   "type": "singlestat",
   "description": "The number of Nuxeo nodes in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.nuxeo.instance-up.count)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "description": "The number of errors in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.log4j.Appender.{error,fatal}.count)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "description": "The number of warnings in the Nuxeo's log for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.log4j.Appender.warn.count)"
    }
   ]
  },
  {
   "title": "All",
   "type": "singlestat",
   "description": "The Nuxeo's log activity for the running instances.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.*.nuxeo.org.apache.log4j.Appender.all.count)"
    }
   ]
  },
  {
   "title": "Errors and warnings",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.log4j.Appender.error.count, 7)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.log4j.Appender.fatal.count, 7)"
    },
    {
     "target": "aliasByNode(servers.*.nuxeo.org.apache.log4j.Appender.warn.count, 7)"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(servers.*.nuxeo.jvm.threads.*.count, 1), 4)"
      }
     ]
    },
    {
     "title": "Threads per JVM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.threads.count, 1)"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.heap.usage, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.memory.*.used, 1, 5)"
      }
     ]
    },
    {
     "title": "Garbage Collector",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.PS-MarkSweep.time, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.garbage.PS-Scavenge.time, 1, 5)"
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.jvm.buffers.*.used, 1, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Repository",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.sessions, 1)"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.jdbc.nuxeo.connections.*, 1, 7, 8)"
      }
     ]
    },
    {
     "title": "Documents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.default.documents.*.count, 1, 7)"
      }
     ]
    },
    {
     "title": "Queries and Saves",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.repositories.default.*.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Transactions concurrency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.concurrents.count.count, 1, 6)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.concurrents.max.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Transactions count and rollback",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.rollbacks.count, 1, 5)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.transactions.duration.count, 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Elasticsearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastic throughputs 1min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.m1_rate, 1, 6)"
      }
     ]
    },
    {
     "title": "Elastic counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Elastic timers p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.p50, 1, 6, 7)"
      }
     ]
    },
    {
     "title": "Elastic timers p98",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.elasticsearch.service.*.p98, 1, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo WorkManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Works completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.total.*.completed, 1, 6)"
      }
     ]
    },
    {
     "title": "Works scheduled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.total.*.scheduled, 1, 6)"
      }
     ]
    },
    {
     "title": "Work timers p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.*.*.p50, 1, 5)"
      }
     ]
    },
    {
     "title": "Work timers p98",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.*.*.p98, 1, 5)"
      }
     ]
    },
    {
     "title": "Works throuhgputs 1min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.works.*.*.m1_rate, 1, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nuxeo Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Auth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.web.authentication.logged-users.count, 1, 6)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.web.authentication.requests.count.count, 1, 6)"
      }
     ]
    },
    {
     "title": "Cache Hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.cache.*.read-hit-ratio, 1, 5)"
      }
     ]
    },
    {
     "title": "Directories sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.*.sessions.active.count, 1, 5, 7)"
      },
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.*.sessions.max.count, 1, 5, 7)"
      }
     ]
    },
    {
     "title": "Directories cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(servers.*.nuxeo.nuxeo.directories.*.cache.size.count, 1, 5)"
      }
     ]
    }
   ]
  }
 ]
}